### ISSUE TITLE
Repozytoria

### ISSUE THREAD

**Issue by KrzysztofDolanski** [JAVAgda40Testowanie/Trener#1]
Cześć Trenerze, Chyba nie możemy załączać naszych projektów (wyświetla mi przy robieniu push: 
Push failed Remote: Repository not found. repository 'https://github.com/JAVAgda40Testowanie/Krzysztof-Dolanski.git/' not found

**Comment by Manfed** [comment]
Hej!
Możesz podać krok po kroku jakie polecenia wydałeś?
Pomoże mi to w szukaniu rozwiązania problemu

**Comment by Manfed** [comment]
Zmieniłem też prawa dostępu do repozytoriów, spróbuj jeszcze raz jakbyś mógł

**Comment by KrzysztofDolanski** [comment]
W remotes ścieżkę dostępu mam podaną, plik gitignore mam zrobiony, robię comit bez problemu, ale jak robię push to teraz mam: Push rejected Push to origin/master was rejected

**Comment by Manfed** [comment]
Może chodzi o to, że na repozytorium znajduje się już plik README.md, którego nie masz u siebie.
Spróbuj użyć ` git pull` przed pushem, żeby zaktualizować repozytorium na swoim komputerze.

**Comment by KrzysztofDolanski** [comment]
nadal błąd

22:44	Git Pull Failed
			POST git-upload-pack (375 bytes)
			warning: no common commits
			remote: Enumerating objects: 6, done.
			remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0
			From https://github.com/JAVAgda40Testowanie/Krzysztof-Dolanski
			* branch            master     -> FETCH_HEAD
			* [new branch]      master     -> origin/master
			refusing to merge unrelated histories

**Comment by Manfed** [comment]
Wydaje mi się, że jest to spowodowane tym, że nie ściągnąłes historii z repozytorium na początku pracy. Proponuję zacząć pracę od użycia polecenia `git clone <link do repozytorium>` i dopiero wtedy nakładanie swoich zmian.

Wszystko dlatego, że repozytoria, które dostaliście miały już jakieś pliki wewnątrz.

**Comment by KrzysztofDolanski** [comment]
1. Jeśli pobieram repozytorium z Krzysztof-Dolański to otrzymuję projekt w postaci tylko pliku readme.(nie ma struktury katalogów ani plików java, czyli src->main->java etc.).


2. Jeśli pobieram Twój projekt to nie mogę zrobić rebase (wyświetla się Can't perform Github rebase GitHub repository 'Trener' is not a fork)

3. Jeśli Pobieram Twój projekt i zmieniam ścieżkę HTTPS w VCS->GIT->Remotes to po zrobieniu push wyświetla że trzeba zrobić marge ale po marge wyświetla (Push rejected Push was rejected, and update failed with error.)

**Comment by marcinkruszynskicarfax** [comment]
Udało mi się zaktualizować repozytorium Oleny używając komend terminala:
```
git clone https://github.com/JAVAgda40Testowanie/Olena-Iusupowa.git
cd Olena-Iusupowa
git remote add trener https://github.com/JAVAgda40Testowanie/Trener.git
git pull trener master --allow-unrelated-histories
git push origin master
```

Jeśli używasz czegoś innego niż terminala do obsługi gita to możemy przysiąść razem i ogarnąć jak to zrobić.

Co do pytań:
1. Jest tylko jeden plik, bo jak spojrzysz na swoje repozytorium, to tylko ten plik tam jest
2. Po pobraniu mojego repo możesz po prostu podmienić remote'a na swoje repo i potem powinno się udać zrobić pusha z flagą `--force`

**Comment by KrzysztofDolanski** [comment]
Dziękuję, działa.
